In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect('database.sqlite')
conn

In [3]:
def sql_query (q):
    return pd.read_sql_query(q,conn)

In [7]:
sql_query('select *from salaries')

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [9]:
q = 'select *from salaries'
sql_query (q)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [11]:
q = 'pragma table_info (salaries)'
sql_query(q)

    cid              name     type  notnull dflt_value  pk
0     0                Id  INTEGER        0       None   1
1     1      EmployeeName     TEXT        0       None   0
2     2          JobTitle     TEXT        0       None   0
3     3           BasePay  NUMERIC        0       None   0
4     4       OvertimePay  NUMERIC        0       None   0
5     5          OtherPay  NUMERIC        0       None   0
6     6          Benefits  NUMERIC        0       None   0
7     7          TotalPay  NUMERIC        0       None   0
8     8  TotalPayBenefits  NUMERIC        0       None   0
9     9              Year  INTEGER        0       None   0
10   10             Notes     TEXT        0       None   0
11   11            Agency     TEXT        0       None   0
12   12            Status     TEXT        0       None   0

#### **1. What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')**

In [15]:
q = """Select jobtitle, avg(totalpaybenefits) as averagetotalpaybenefits from salaries where jobtitle not in ('Not Provided', 'Not provided')
group by jobtitle order by averagetotalpaybenefits desc;"""
sql_query (q)

                                            JobTitle  averagetotalpaybenefits
0                           Chief Investment Officer            436224.360000
1                                    Chief of Police            411732.266667
2                             Chief, Fire Department            408865.326667
3     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY            399211.275000
4                         Gen Mgr, Public Trnsp Dept            380696.440000
...                                              ...                      ...
2153                           SPECIAL ASSISTANT XIV               673.800000
2154              BOARD/COMMISSION MEMBER, GROUP III               638.787879
2155                      BdComm Mbr, Grp2,M=$25/Mtg               475.047742
2156               BOARD/COMMISSION MEMBER, GROUP II               296.511628
2157         PUBLIC SAFETY COMMUNICATIONS TECHNICIAN               149.510000

[2158 rows x 2 columns]

#### **2. Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000**

In [16]:
q = """Select jobtitle,overtimepay from salaries where overtimepay > 50000;"""
sql_query (q)

                                              JobTitle   OvertimePay
0                      CAPTAIN III (POLICE DEPARTMENT)     106088.18
1                 WIRE ROPE CABLE MAINTENANCE MECHANIC      56120.71
2                   BATTALION CHIEF, (FIRE DEPARTMENT)       89062.9
3                   BATTALION CHIEF, (FIRE DEPARTMENT)      86362.68
4     ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)      71344.88
...                                                ...           ...
2163                           Parking Control Officer      54738.36
2164                                      Not provided  Not Provided
2165                                      Not provided  Not Provided
2166                                      Not provided  Not Provided
2167                                      Not provided  Not Provided

[2168 rows x 2 columns]

#### **3. What is the total number of unique employees? exclude ('Not Provided', 'Not provided')**

In [18]:
q = """Select count(distinct id) as uniqueemployees from salaries where id not in ('not provided', 'not provided');"""
sql_query(q)

   uniqueemployees
0           148653

#### **4.Show The Top 10 highest Paid Employees**

In [19]:
q = """select employeename, jobtitle, totalpaybenefits from salaries order by totalpaybenefits desc limit 10"""
sql_query(q)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
5,Joanne M Hayes-White,"Chief, Fire Department",422353.40
6,Gregory P Suhr,Chief of Police,418019.22
7,Joanne M Hayes-White,"Chief, Fire Department",417435.10
8,Ellen G Moffatt,Asst Med Examiner,415767.94
9,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

#### **5.Show All Employees Ordered By Their TotalPay Benefits In Descending Order**

In [22]:
q = """Select EmployeeName, JobTitle, TotalPayBenefits From Salaries order by TotalPayBenefits desc;"""
sql_query (q)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
...,...,...,...
148648,Not provided,Not provided,0.00
148649,Timothy E Gibson,Police Officer 3,-2.73
148650,Mark E Laherty,Police Officer 3,-8.20
148651,David P Kucia,Police Officer 3,-33.89
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13